<?php
/**
 * @copyright © 2017 by Solazu Co.,LTD
 * @project Learn Master Plugin
 *
 * @since 1.0
 *
 */


namespace lema\helpers\validators;


use lema\core\BaseObject;
use lema\core\interfaces\ValidatorInterface;
use lema\core\Validator;

class TextValidator extends Validator implements ValidatorInterface
{
    /**
     * @var bool
     */
    public $required = false;

    /**
     * @var int
     */
    public $length = 4096;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function validate()
    {
        if ($this->required && empty($this->content)) {
            return false;
        }
        if (strlen($this->content) > $this->length) {
            return false;
        }
        return true;
    }


}