<?php
/**
 * @project  edu
 * @copyright © 2017 by ivoglent
 * @author ivoglent
 * @time  7/20/17.
 */


namespace lema\admin\controllers;


use lema\core\Controller;
use lema\core\interfaces\ControllerInterface;

class CourseLevelController extends AdminController implements ControllerInterface
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Register all actions that controller want to hook
     * @return mixed
     */
    public static function registerAction()
    {

	    return [
            'actions' => [],
            'ajax' => [],
        ];
    }

    /**
     * get option data
     * @return [object] 
     */
    public function getOptions() {
        $model = \lema\models\CourseLevelModel::getInstance();
        return $model->getOptions();
    }
    
}