<?php
/**
 * @project  edu
 * @copyright © 2017 by ivoglent
 * @author ivoglent
 * @time  8/7/17.
 */


namespace lema\core\components;


use lema\core\BaseObject;
use lema\core\interfaces\ComponentInterface;
use lema\core\interfaces\MigrableInterface;


class Migration extends BaseObject implements ComponentInterface
{
    const DB_VERSION_NAME           = 'lema_db_version';
    const LEMA_VERSION_NAME         = 'lema_version';

    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * Check db version and up/down-grade
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    /**
     * @return array
     */
    private function getMigrationObjects()
    {
        $locations = [
            'lema\core' => '',
            'lema\helpers' => 'Helper',
            'lema\extensions' => 'Extension',
            'lema\migrations' => 'Migration',
            'lema\models' => 'Model'];
        $migrations = [];
        foreach ($locations as $namespace => $type) {
            $m  = lema()->helpers->file->findAllClass($namespace, $type, '\lema\core\interfaces\MigrableInterface');
            $migrations = array_merge($migrations, $m);
        }
        return $migrations;
    }

    /**
     * Run when Lema need to upgrade db or code
     *
     */
    public function up()
    {
        $migrations = $this->getMigrationObjects();
        foreach ($migrations as $class) {
            /** @var MigrableInterface $migrator */
            $migrator = new $class();
            $migrator->onActivate();
        }
    }

    /**
     * Run if lema uninstall
     */
    public function down()
    {
        $migrations = $this->getMigrationObjects();
        foreach ($migrations as $class) {
            /** @var MigrableInterface $migrator */
            $migrator = new $class();
            $migrator->onDeactivate();
        }
    }

    /**
     * Run uninstall tasks
     */
    public function uninstall()
    {
        $migrations = $this->getMigrationObjects();
        foreach ($migrations as $class) {
            /** @var MigrableInterface $migrator */
            $migrator = new $class();
            $migrator->onUninstall();
        }
    }

    /**
     * Show upgrade success message
     */
    public function upgradeSuccess()
    {
        $message = ' <div class="notice notice-success is-dismissible"><p>%s</p></div>';
        echo sprintf($message, __('Learn Master plugin currently upgraded successfully to new version : ' . LEMA_VERSION, 'lema'));
    }
    /**
     * Upgrade all component when new version of lema is installed
     */
    public function upgrade()
    {
        $migrations = $this->getMigrationObjects();
        foreach ($migrations as $class) {
            /** @var MigrableInterface $migrator */
            $migrator = new $class();
            $migrator->onUpgrade(LEMA_VERSION);
        }
        add_action( 'admin_notices', [$this, 'upgradeSuccess'] );
        lema()->config->lema_version = LEMA_VERSION;
    }
}