<?php
/**
 * @copyright © 2017 by Solazu Co.,LTD
 * @project Learn Master Plugin
 *
 * @since 1.0
 *
 */



namespace lema\shortcodes\course\shortcodes;



use lema\core\Shortcode;

class CourseFooterShortcode extends Shortcode
{
    const SHORTCODE_ID             = 'lema_course_footer';
    public $contentView            = 'footer';
    /**
     * Get Id of shortcode
     * @return string
     */
    public function getId()
    {
        return self::SHORTCODE_ID;
    }

    /**
     * @param array $data
     * @param string $content
     * @return string
     */
    public function getShortcodeContent($data = [], $content = '', $key = '')
    {
        $shortcodeContent = lema_do_shortcode($content);
        return parent::getShortcodeContent($data, ['content' => $shortcodeContent]); // TODO: Change the autogenerated stub
    }
}