<?php

namespace lema\models;

use lema\core\Model;
use lema\core\interfaces\ModelInterface;

class BundleModel extends Model implements ModelInterface {


	const POST_TYPE = 'lema_bundle';
	const POST_META = 'course_meta';
	const BUNDLE_ID = 'bundle_id';
	const SALE_PRICE = 'lema_sale_price';
	const REGULAR_PRICE = 'total_price';


	public static function getPosttypeConfig() {
		// TODO: Implement getPosttypeConfig() method.
		$labels = array(
			'name'               => _x( 'Bundle', 'post type general name', 'lema' ),
			'singular_name'      => _x( 'Bundle', 'post type singular name', 'lema' ),
			'menu_name'          => _x( 'Bundle', 'admin menu', 'lema' ),
			'name_admin_bar'     => _x( 'Bundle', 'add new on admin bar', 'lema' ),
			'add_new'            => _x( 'Add Bundle', 'Course', 'lema' ),
			'add_new_item'       => __( 'Add New Bundle', 'lema' ),
			'new_item'           => __( 'New Bundle', 'lema' ),
			'edit_item'          => __( 'Edit Bundle', 'lema' ),
			'view_item'          => __( 'View Bundle', 'lema' ),
			'all_items'          => __( 'Bundles', 'lema' ),
			'search_items'       => __( 'Search Bundle', 'lema' ),
			'parent_item_colon'  => __( 'Parent Bundle:', 'lema' ),
			'not_found'          => __( 'No Bundle found.', 'lema' ),
			'not_found_in_trash' => __( 'No Bundle found in Trash.', 'lema' )
		);

		$args = array(
			'labels'          => $labels,
			'description'     => __( 'Description.', 'lema' ),
			'public'          => true,
			'show_ui'         => true,
			'show_in_menu'    => true,
			'capability_type' => 'post',
			'has_archive'     => false,
			'hierarchical'    => false,
			'supports'        => array( 'title', 'excerpt', 'thumbnail' )
		);

		return [
			'post' => [
				'name' => 'lema_bundle',
				'args' => $args
			]
		];
	}

	public function getId() {
		return parent::getId(); // TODO: Change the autogenerated stub
	}

	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function getName() {
		return self::POST_TYPE;
	}

	public function save( $postData = [] ) {
		try {
			$defaultPostData = [
				'post_title'  => '#Bundle ',
				'post_type'   => self::POST_TYPE,
				'post_status' => 'publish'
			];
			if ( $this->isNew ) {
				$postId = wp_insert_post( array_merge( $defaultPostData, $postData ) );

				return $postId;
			} else {
				return wp_update_post( $this->post );
			}
		} catch ( \Exception $e ) {
		}

		return false;
	}

	public function saveMetaData( $post_id, $data_meta ) {
		if ( isset( $data_meta['instructors'] ) && ! empty( $data_meta['instructors'] ) ) {

			if ( is_array( $data_meta['instructors'] ) ) {
				foreach ( $data_meta['instructors'] as $ins_id ) {
					add_user_meta( $ins_id, Instructor::instructorMetaKey(), $post_id );
				}
			}
		}
		$attrs = $this->getAttributes();
		foreach ( $attrs as $key => $data ) {
			if ( isset( $data_meta[ $key ] ) ) {
				update_post_meta( $post_id, $key, $data_meta[ $key ] );
			} else {
				update_post_meta( $post_id, $key, '' );
			}
		}
	}

	public function getAttributes() {

		return array(
			'instructors'           => '',
			self::SALE_PRICE        => '',
			self::REGULAR_PRICE     => '',
			'best_selling'          => '',
			'lema_subtitle_text'    => '',
			'lema_about_area'       => '',
			'lema_project_area'     => '',
			'created_by_conditinal' => '',
			'creator_by_conditinal' => '',
			'lema_faq_repeator'     => '',
		);


	}

	public static function get_list_course_bundle( $post_id ) {

		$bundle_item = get_post_meta( $post_id, self::POST_META );

		if ( ! empty( $bundle_item ) && is_array( $bundle_item ) ) {
			return $bundle_item;

		} else {
			return array();
		}

	}

	/**
	 * Get instructors list who assigned to this course
	 *
	 * @param int $postId
	 *
	 * @return array
	 */
	public function getInstructors( $postId = false, $object = '', $limit = - 1 ) {

		$instructors = [];
		if ( $postId == false ) {
			return $instructors;
		}
		$user_query = new \WP_User_Query(
			array(
				'meta_key'   => Instructor::instructorMetaKey(),
				'meta_value' => $postId ? $postId : $this->getId()
			)
		);
		/*Array
		(
            [0] => Array
            (
                [0] => 4
                [1] => 5
            ))*/
		$instructs_geted      = get_post_meta( $postId, 'instructors' );
		$post_meta_instructor = array_shift( $instructs_geted );
		$limit                = intval( $limit );
		$users                = $user_query->get_results();
		foreach ( $users as $i => $user ) {
			/** @var \WP_User $user */
			if ( is_array( $post_meta_instructor ) && in_array( $user->ID, $post_meta_instructor ) ) {
				if ( $object !== '' ) {
					$instructors[ $user->ID ] = $user;
				} else {
					$instructors[ $user->ID ] = $user->display_name;
				}
			} else {
				delete_user_meta( $user->ID, Instructor::instructorMetaKey(), $postId );
			}

			if ( $limit > 0 && $i == $limit - 1 ) {
				break;
			}
		}

		return $instructors;
	}

	public static function getAll() {

		$args  = array(
			'post_type'   => BundleModel::POST_TYPE,
			'post_status' => 'publish'
		);
		$query = new \WP_Query( $args );

		return $query->posts;

	}

	public function delete() {
	}
	//Add
	public function getViewNumber( $courseID = false ) {

		$view_count = 0;
		if ( $courseID ) {
			$course_view_count = get_post_meta( $courseID, 'bundle_view_count', true );
			$view_count        = ! empty( $course_view_count ) ? $course_view_count : $view_count;
		}

		return $view_count;
	}
}